version: "3.9"
services:
  app:
    build: .
    container_name: revend-app
    ports:
      - "5000:5000"
    volumes:
      - .:/code
    
  db:
    container_name: db
    image: postgres:15.1-alpine
    ports: 
      - 5432
    env_file:
      - .env