version: "3.9"
services:
  app:
    build: .
    container_name: revend-app
    ports:
      - "5000:5000"
    volumes:
      - .:/code
    environment:
      FLASK_CONFIG: development
      FLASK_DEBUG: True
    
  db:
    container_name: db
    image: postgres:latest
    ports: 
      - 5433:5432
    env_file:
      - .env

  
  db-test:
    container_name: db-test
    image: postgres:latest
    ports: 
      - 5432:5433
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pgpassword
      POSTGRES_DB: postgres